export const DEFAULT_CURRENCY = {
  country: 'Nigeria',
  countryCode: 'NG',
  currencyCode: 'NGN',
  currencyName: 'Nigerian Naira',
  symbol: '₦',
}

export const CURRENCIES = [
  { country: 'Afghanistan', countryCode: 'AF', currencyCode: 'AFN', currencyName: 'Afghan Afghani', symbol: '؋' },
  { country: 'Albania', countryCode: 'AL', currencyCode: 'ALL', currencyName: 'Albanian Lek', symbol: 'L' },
  { country: 'Algeria', countryCode: 'DZ', currencyCode: 'DZD', currencyName: 'Algerian Dinar', symbol: 'دج' },
  { country: 'Andorra', countryCode: 'AD', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Angola', countryCode: 'AO', currencyCode: 'AOA', currencyName: 'Angolan Kwanza', symbol: 'Kz' },
  { country: 'Antigua and Barbuda', countryCode: 'AG', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Argentina', countryCode: 'AR', currencyCode: 'ARS', currencyName: 'Argentine Peso', symbol: '$' },
  { country: 'Armenia', countryCode: 'AM', currencyCode: 'AMD', currencyName: 'Armenian Dram', symbol: '֏' },
  { country: 'Australia', countryCode: 'AU', currencyCode: 'AUD', currencyName: 'Australian Dollar', symbol: '$' },
  { country: 'Austria', countryCode: 'AT', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Azerbaijan', countryCode: 'AZ', currencyCode: 'AZN', currencyName: 'Azerbaijani Manat', symbol: '₼' },
  { country: 'Bahamas', countryCode: 'BS', currencyCode: 'BSD', currencyName: 'Bahamian Dollar', symbol: '$' },
  { country: 'Bahrain', countryCode: 'BH', currencyCode: 'BHD', currencyName: 'Bahraini Dinar', symbol: '.د.ب' },
  { country: 'Bangladesh', countryCode: 'BD', currencyCode: 'BDT', currencyName: 'Bangladeshi Taka', symbol: '৳' },
  { country: 'Barbados', countryCode: 'BB', currencyCode: 'BBD', currencyName: 'Barbadian Dollar', symbol: '$' },
  { country: 'Belarus', countryCode: 'BY', currencyCode: 'BYN', currencyName: 'Belarusian Ruble', symbol: 'Br' },
  { country: 'Belgium', countryCode: 'BE', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Belize', countryCode: 'BZ', currencyCode: 'BZD', currencyName: 'Belize Dollar', symbol: '$' },
  { country: 'Benin', countryCode: 'BJ', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Bhutan', countryCode: 'BT', currencyCode: 'BTN', currencyName: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  { country: 'Bolivia', countryCode: 'BO', currencyCode: 'BOB', currencyName: 'Bolivian Boliviano', symbol: 'Bs.' },
  { country: 'Bosnia and Herzegovina', countryCode: 'BA', currencyCode: 'BAM', currencyName: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
  { country: 'Botswana', countryCode: 'BW', currencyCode: 'BWP', currencyName: 'Botswana Pula', symbol: 'P' },
  { country: 'Brazil', countryCode: 'BR', currencyCode: 'BRL', currencyName: 'Brazilian Real', symbol: 'R$' },
  { country: 'Brunei', countryCode: 'BN', currencyCode: 'BND', currencyName: 'Brunei Dollar', symbol: '$' },
  { country: 'Bulgaria', countryCode: 'BG', currencyCode: 'BGN', currencyName: 'Bulgarian Lev', symbol: 'лв' },
  { country: 'Burkina Faso', countryCode: 'BF', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Burundi', countryCode: 'BI', currencyCode: 'BIF', currencyName: 'Burundian Franc', symbol: 'FBu' },
  { country: 'Cabo Verde', countryCode: 'CV', currencyCode: 'CVE', currencyName: 'Cape Verdean Escudo', symbol: '$' },
  { country: 'Cambodia', countryCode: 'KH', currencyCode: 'KHR', currencyName: 'Cambodian Riel', symbol: '៛' },
  { country: 'Cameroon', countryCode: 'CM', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Canada', countryCode: 'CA', currencyCode: 'CAD', currencyName: 'Canadian Dollar', symbol: '$' },
  { country: 'Central African Republic', countryCode: 'CF', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Chad', countryCode: 'TD', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Chile', countryCode: 'CL', currencyCode: 'CLP', currencyName: 'Chilean Peso', symbol: '$' },
  { country: 'China', countryCode: 'CN', currencyCode: 'CNY', currencyName: 'Chinese Yuan', symbol: '¥' },
  { country: 'Colombia', countryCode: 'CO', currencyCode: 'COP', currencyName: 'Colombian Peso', symbol: '$' },
  { country: 'Comoros', countryCode: 'KM', currencyCode: 'KMF', currencyName: 'Comorian Franc', symbol: 'CF' },
  { country: 'Congo (DRC)', countryCode: 'CD', currencyCode: 'CDF', currencyName: 'Congolese Franc', symbol: 'FC' },
  { country: 'Congo (Republic)', countryCode: 'CG', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Costa Rica', countryCode: 'CR', currencyCode: 'CRC', currencyName: 'Costa Rican Colón', symbol: '₡' },
  { country: "Côte d'Ivoire", countryCode: 'CI', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Croatia', countryCode: 'HR', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Cuba', countryCode: 'CU', currencyCode: 'CUP', currencyName: 'Cuban Peso', symbol: '$' },
  { country: 'Cyprus', countryCode: 'CY', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Czechia', countryCode: 'CZ', currencyCode: 'CZK', currencyName: 'Czech Koruna', symbol: 'Kč' },
  { country: 'Denmark', countryCode: 'DK', currencyCode: 'DKK', currencyName: 'Danish Krone', symbol: 'kr' },
  { country: 'Djibouti', countryCode: 'DJ', currencyCode: 'DJF', currencyName: 'Djiboutian Franc', symbol: 'Fdj' },
  { country: 'Dominica', countryCode: 'DM', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Dominican Republic', countryCode: 'DO', currencyCode: 'DOP', currencyName: 'Dominican Peso', symbol: 'RD$' },
  { country: 'Ecuador', countryCode: 'EC', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Egypt', countryCode: 'EG', currencyCode: 'EGP', currencyName: 'Egyptian Pound', symbol: 'ج.م' },
  { country: 'El Salvador', countryCode: 'SV', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Equatorial Guinea', countryCode: 'GQ', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Eritrea', countryCode: 'ER', currencyCode: 'ERN', currencyName: 'Eritrean Nakfa', symbol: 'Nfk' },
  { country: 'Estonia', countryCode: 'EE', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Eswatini', countryCode: 'SZ', currencyCode: 'SZL', currencyName: 'Swazi Lilangeni', symbol: 'L' },
  { country: 'Ethiopia', countryCode: 'ET', currencyCode: 'ETB', currencyName: 'Ethiopian Birr', symbol: 'Br' },
  { country: 'Fiji', countryCode: 'FJ', currencyCode: 'FJD', currencyName: 'Fijian Dollar', symbol: '$' },
  { country: 'Finland', countryCode: 'FI', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'France', countryCode: 'FR', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Gabon', countryCode: 'GA', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', symbol: 'FCFA' },
  { country: 'Gambia', countryCode: 'GM', currencyCode: 'GMD', currencyName: 'Gambian Dalasi', symbol: 'D' },
  { country: 'Georgia', countryCode: 'GE', currencyCode: 'GEL', currencyName: 'Georgian Lari', symbol: '₾' },
  { country: 'Germany', countryCode: 'DE', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Ghana', countryCode: 'GH', currencyCode: 'GHS', currencyName: 'Ghanaian Cedi', symbol: 'GH₵' },
  { country: 'Greece', countryCode: 'GR', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Grenada', countryCode: 'GD', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Guatemala', countryCode: 'GT', currencyCode: 'GTQ', currencyName: 'Guatemalan Quetzal', symbol: 'Q' },
  { country: 'Guinea', countryCode: 'GN', currencyCode: 'GNF', currencyName: 'Guinean Franc', symbol: 'FG' },
  { country: 'Guinea-Bissau', countryCode: 'GW', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Guyana', countryCode: 'GY', currencyCode: 'GYD', currencyName: 'Guyanese Dollar', symbol: '$' },
  { country: 'Haiti', countryCode: 'HT', currencyCode: 'HTG', currencyName: 'Haitian Gourde', symbol: 'G' },
  { country: 'Honduras', countryCode: 'HN', currencyCode: 'HNL', currencyName: 'Honduran Lempira', symbol: 'L' },
  { country: 'Hong Kong', countryCode: 'HK', currencyCode: 'HKD', currencyName: 'Hong Kong Dollar', symbol: '$' },
  { country: 'Hungary', countryCode: 'HU', currencyCode: 'HUF', currencyName: 'Hungarian Forint', symbol: 'Ft' },
  { country: 'Iceland', countryCode: 'IS', currencyCode: 'ISK', currencyName: 'Icelandic Króna', symbol: 'kr' },
  { country: 'India', countryCode: 'IN', currencyCode: 'INR', currencyName: 'Indian Rupee', symbol: '₹' },
  { country: 'Indonesia', countryCode: 'ID', currencyCode: 'IDR', currencyName: 'Indonesian Rupiah', symbol: 'Rp' },
  { country: 'Iran', countryCode: 'IR', currencyCode: 'IRR', currencyName: 'Iranian Rial', symbol: '﷼' },
  { country: 'Iraq', countryCode: 'IQ', currencyCode: 'IQD', currencyName: 'Iraqi Dinar', symbol: 'ع.د' },
  { country: 'Ireland', countryCode: 'IE', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Israel', countryCode: 'IL', currencyCode: 'ILS', currencyName: 'Israeli New Shekel', symbol: '₪' },
  { country: 'Italy', countryCode: 'IT', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Jamaica', countryCode: 'JM', currencyCode: 'JMD', currencyName: 'Jamaican Dollar', symbol: '$' },
  { country: 'Japan', countryCode: 'JP', currencyCode: 'JPY', currencyName: 'Japanese Yen', symbol: '¥' },
  { country: 'Jordan', countryCode: 'JO', currencyCode: 'JOD', currencyName: 'Jordanian Dinar', symbol: 'د.ا' },
  { country: 'Kazakhstan', countryCode: 'KZ', currencyCode: 'KZT', currencyName: 'Kazakhstani Tenge', symbol: '₸' },
  { country: 'Kenya', countryCode: 'KE', currencyCode: 'KES', currencyName: 'Kenyan Shilling', symbol: 'KSh' },
  { country: 'Kiribati', countryCode: 'KI', currencyCode: 'AUD', currencyName: 'Australian Dollar', symbol: '$' },
  { country: 'Kosovo', countryCode: 'XK', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Kuwait', countryCode: 'KW', currencyCode: 'KWD', currencyName: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { country: 'Kyrgyzstan', countryCode: 'KG', currencyCode: 'KGS', currencyName: 'Kyrgyzstani Som', symbol: 'с' },
  { country: 'Laos', countryCode: 'LA', currencyCode: 'LAK', currencyName: 'Lao Kip', symbol: '₭' },
  { country: 'Latvia', countryCode: 'LV', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Lebanon', countryCode: 'LB', currencyCode: 'LBP', currencyName: 'Lebanese Pound', symbol: 'ل.ل' },
  { country: 'Lesotho', countryCode: 'LS', currencyCode: 'LSL', currencyName: 'Lesotho Loti', symbol: 'L' },
  { country: 'Liberia', countryCode: 'LR', currencyCode: 'LRD', currencyName: 'Liberian Dollar', symbol: '$' },
  { country: 'Libya', countryCode: 'LY', currencyCode: 'LYD', currencyName: 'Libyan Dinar', symbol: 'ل.د' },
  { country: 'Liechtenstein', countryCode: 'LI', currencyCode: 'CHF', currencyName: 'Swiss Franc', symbol: 'CHF' },
  { country: 'Lithuania', countryCode: 'LT', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Luxembourg', countryCode: 'LU', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Madagascar', countryCode: 'MG', currencyCode: 'MGA', currencyName: 'Malagasy Ariary', symbol: 'Ar' },
  { country: 'Malawi', countryCode: 'MW', currencyCode: 'MWK', currencyName: 'Malawian Kwacha', symbol: 'MK' },
  { country: 'Malaysia', countryCode: 'MY', currencyCode: 'MYR', currencyName: 'Malaysian Ringgit', symbol: 'RM' },
  { country: 'Maldives', countryCode: 'MV', currencyCode: 'MVR', currencyName: 'Maldivian Rufiyaa', symbol: '.ރ' },
  { country: 'Mali', countryCode: 'ML', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Malta', countryCode: 'MT', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Marshall Islands', countryCode: 'MH', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Mauritania', countryCode: 'MR', currencyCode: 'MRU', currencyName: 'Mauritanian Ouguiya', symbol: 'UM' },
  { country: 'Mauritius', countryCode: 'MU', currencyCode: 'MUR', currencyName: 'Mauritian Rupee', symbol: '₨' },
  { country: 'Mexico', countryCode: 'MX', currencyCode: 'MXN', currencyName: 'Mexican Peso', symbol: '$' },
  { country: 'Micronesia', countryCode: 'FM', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Moldova', countryCode: 'MD', currencyCode: 'MDL', currencyName: 'Moldovan Leu', symbol: 'L' },
  { country: 'Monaco', countryCode: 'MC', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Mongolia', countryCode: 'MN', currencyCode: 'MNT', currencyName: 'Mongolian Tögrög', symbol: '₮' },
  { country: 'Montenegro', countryCode: 'ME', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Morocco', countryCode: 'MA', currencyCode: 'MAD', currencyName: 'Moroccan Dirham', symbol: 'د.م.' },
  { country: 'Mozambique', countryCode: 'MZ', currencyCode: 'MZN', currencyName: 'Mozambican Metical', symbol: 'MT' },
  { country: 'Myanmar', countryCode: 'MM', currencyCode: 'MMK', currencyName: 'Myanmar Kyat', symbol: 'K' },
  { country: 'Namibia', countryCode: 'NA', currencyCode: 'NAD', currencyName: 'Namibian Dollar', symbol: '$' },
  { country: 'Nauru', countryCode: 'NR', currencyCode: 'AUD', currencyName: 'Australian Dollar', symbol: '$' },
  { country: 'Nepal', countryCode: 'NP', currencyCode: 'NPR', currencyName: 'Nepalese Rupee', symbol: '₨' },
  { country: 'Netherlands', countryCode: 'NL', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'New Zealand', countryCode: 'NZ', currencyCode: 'NZD', currencyName: 'New Zealand Dollar', symbol: '$' },
  { country: 'Nicaragua', countryCode: 'NI', currencyCode: 'NIO', currencyName: 'Nicaraguan Córdoba', symbol: 'C$' },
  { country: 'Niger', countryCode: 'NE', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Nigeria', countryCode: 'NG', currencyCode: 'NGN', currencyName: 'Nigerian Naira', symbol: '₦' },
  { country: 'North Korea', countryCode: 'KP', currencyCode: 'KPW', currencyName: 'North Korean Won', symbol: '₩' },
  { country: 'North Macedonia', countryCode: 'MK', currencyCode: 'MKD', currencyName: 'Macedonian Denar', symbol: 'ден' },
  { country: 'Norway', countryCode: 'NO', currencyCode: 'NOK', currencyName: 'Norwegian Krone', symbol: 'kr' },
  { country: 'Oman', countryCode: 'OM', currencyCode: 'OMR', currencyName: 'Omani Rial', symbol: 'ر.ع.' },
  { country: 'Pakistan', countryCode: 'PK', currencyCode: 'PKR', currencyName: 'Pakistani Rupee', symbol: '₨' },
  { country: 'Palau', countryCode: 'PW', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Palestine', countryCode: 'PS', currencyCode: 'ILS', currencyName: 'Israeli New Shekel', symbol: '₪' },
  { country: 'Panama', countryCode: 'PA', currencyCode: 'PAB', currencyName: 'Panamanian Balboa', symbol: 'B/.' },
  { country: 'Papua New Guinea', countryCode: 'PG', currencyCode: 'PGK', currencyName: 'Papua New Guinean Kina', symbol: 'K' },
  { country: 'Paraguay', countryCode: 'PY', currencyCode: 'PYG', currencyName: 'Paraguayan Guaraní', symbol: '₲' },
  { country: 'Peru', countryCode: 'PE', currencyCode: 'PEN', currencyName: 'Peruvian Sol', symbol: 'S/.' },
  { country: 'Philippines', countryCode: 'PH', currencyCode: 'PHP', currencyName: 'Philippine Peso', symbol: '₱' },
  { country: 'Poland', countryCode: 'PL', currencyCode: 'PLN', currencyName: 'Polish Złoty', symbol: 'zł' },
  { country: 'Portugal', countryCode: 'PT', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Qatar', countryCode: 'QA', currencyCode: 'QAR', currencyName: 'Qatari Riyal', symbol: 'ر.ق' },
  { country: 'Romania', countryCode: 'RO', currencyCode: 'RON', currencyName: 'Romanian Leu', symbol: 'lei' },
  { country: 'Russia', countryCode: 'RU', currencyCode: 'RUB', currencyName: 'Russian Ruble', symbol: '₽' },
  { country: 'Rwanda', countryCode: 'RW', currencyCode: 'RWF', currencyName: 'Rwandan Franc', symbol: 'FRw' },
  { country: 'Saint Kitts and Nevis', countryCode: 'KN', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Saint Lucia', countryCode: 'LC', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Saint Vincent and the Grenadines', countryCode: 'VC', currencyCode: 'XCD', currencyName: 'East Caribbean Dollar', symbol: '$' },
  { country: 'Samoa', countryCode: 'WS', currencyCode: 'WST', currencyName: 'Samoan Tālā', symbol: 'T' },
  { country: 'San Marino', countryCode: 'SM', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Sao Tome and Principe', countryCode: 'ST', currencyCode: 'STN', currencyName: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
  { country: 'Saudi Arabia', countryCode: 'SA', currencyCode: 'SAR', currencyName: 'Saudi Riyal', symbol: 'ر.س' },
  { country: 'Senegal', countryCode: 'SN', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Serbia', countryCode: 'RS', currencyCode: 'RSD', currencyName: 'Serbian Dinar', symbol: 'дин.' },
  { country: 'Seychelles', countryCode: 'SC', currencyCode: 'SCR', currencyName: 'Seychellois Rupee', symbol: '₨' },
  { country: 'Sierra Leone', countryCode: 'SL', currencyCode: 'SLE', currencyName: 'Sierra Leonean Leone', symbol: 'Le' },
  { country: 'Singapore', countryCode: 'SG', currencyCode: 'SGD', currencyName: 'Singapore Dollar', symbol: '$' },
  { country: 'Slovakia', countryCode: 'SK', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Slovenia', countryCode: 'SI', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Solomon Islands', countryCode: 'SB', currencyCode: 'SBD', currencyName: 'Solomon Islands Dollar', symbol: '$' },
  { country: 'Somalia', countryCode: 'SO', currencyCode: 'SOS', currencyName: 'Somali Shilling', symbol: 'Sh' },
  { country: 'South Africa', countryCode: 'ZA', currencyCode: 'ZAR', currencyName: 'South African Rand', symbol: 'R' },
  { country: 'South Korea', countryCode: 'KR', currencyCode: 'KRW', currencyName: 'South Korean Won', symbol: '₩' },
  { country: 'South Sudan', countryCode: 'SS', currencyCode: 'SSP', currencyName: 'South Sudanese Pound', symbol: '£' },
  { country: 'Spain', countryCode: 'ES', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Sri Lanka', countryCode: 'LK', currencyCode: 'LKR', currencyName: 'Sri Lankan Rupee', symbol: 'Rs' },
  { country: 'Sudan', countryCode: 'SD', currencyCode: 'SDG', currencyName: 'Sudanese Pound', symbol: 'ج.س.' },
  { country: 'Suriname', countryCode: 'SR', currencyCode: 'SRD', currencyName: 'Surinamese Dollar', symbol: '$' },
  { country: 'Sweden', countryCode: 'SE', currencyCode: 'SEK', currencyName: 'Swedish Krona', symbol: 'kr' },
  { country: 'Switzerland', countryCode: 'CH', currencyCode: 'CHF', currencyName: 'Swiss Franc', symbol: 'CHF' },
  { country: 'Syria', countryCode: 'SY', currencyCode: 'SYP', currencyName: 'Syrian Pound', symbol: '£' },
  { country: 'Taiwan', countryCode: 'TW', currencyCode: 'TWD', currencyName: 'New Taiwan Dollar', symbol: 'NT$' },
  { country: 'Tajikistan', countryCode: 'TJ', currencyCode: 'TJS', currencyName: 'Tajikistani Somoni', symbol: 'SM' },
  { country: 'Tanzania', countryCode: 'TZ', currencyCode: 'TZS', currencyName: 'Tanzanian Shilling', symbol: 'TSh' },
  { country: 'Thailand', countryCode: 'TH', currencyCode: 'THB', currencyName: 'Thai Baht', symbol: '฿' },
  { country: 'Timor-Leste', countryCode: 'TL', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Togo', countryCode: 'TG', currencyCode: 'XOF', currencyName: 'West African CFA Franc', symbol: 'CFA' },
  { country: 'Tonga', countryCode: 'TO', currencyCode: 'TOP', currencyName: 'Tongan Paʻanga', symbol: 'T$' },
  { country: 'Trinidad and Tobago', countryCode: 'TT', currencyCode: 'TTD', currencyName: 'Trinidad and Tobago Dollar', symbol: '$' },
  { country: 'Tunisia', countryCode: 'TN', currencyCode: 'TND', currencyName: 'Tunisian Dinar', symbol: 'د.ت' },
  { country: 'Turkey', countryCode: 'TR', currencyCode: 'TRY', currencyName: 'Turkish Lira', symbol: '₺' },
  { country: 'Turkmenistan', countryCode: 'TM', currencyCode: 'TMT', currencyName: 'Turkmenistani Manat', symbol: 'm' },
  { country: 'Tuvalu', countryCode: 'TV', currencyCode: 'AUD', currencyName: 'Australian Dollar', symbol: '$' },
  { country: 'Uganda', countryCode: 'UG', currencyCode: 'UGX', currencyName: 'Ugandan Shilling', symbol: 'USh' },
  { country: 'Ukraine', countryCode: 'UA', currencyCode: 'UAH', currencyName: 'Ukrainian Hryvnia', symbol: '₴' },
  { country: 'United Arab Emirates', countryCode: 'AE', currencyCode: 'AED', currencyName: 'UAE Dirham', symbol: 'د.إ' },
  { country: 'United Kingdom', countryCode: 'GB', currencyCode: 'GBP', currencyName: 'British Pound', symbol: '£' },
  { country: 'United States', countryCode: 'US', currencyCode: 'USD', currencyName: 'US Dollar', symbol: '$' },
  { country: 'Uruguay', countryCode: 'UY', currencyCode: 'UYU', currencyName: 'Uruguayan Peso', symbol: '$' },
  { country: 'Uzbekistan', countryCode: 'UZ', currencyCode: 'UZS', currencyName: 'Uzbekistani Som', symbol: 'сум' },
  { country: 'Vanuatu', countryCode: 'VU', currencyCode: 'VUV', currencyName: 'Vanuatu Vatu', symbol: 'VT' },
  { country: 'Vatican City', countryCode: 'VA', currencyCode: 'EUR', currencyName: 'Euro', symbol: '€' },
  { country: 'Venezuela', countryCode: 'VE', currencyCode: 'VES', currencyName: 'Venezuelan Bolívar', symbol: 'Bs.' },
  { country: 'Vietnam', countryCode: 'VN', currencyCode: 'VND', currencyName: 'Vietnamese Đồng', symbol: '₫' },
  { country: 'Yemen', countryCode: 'YE', currencyCode: 'YER', currencyName: 'Yemeni Rial', symbol: '﷼' },
  { country: 'Zambia', countryCode: 'ZM', currencyCode: 'ZMW', currencyName: 'Zambian Kwacha', symbol: 'ZK' },
  { country: 'Zimbabwe', countryCode: 'ZW', currencyCode: 'ZWL', currencyName: 'Zimbabwean Dollar', symbol: '$' },
]