export const DEFAULT_COUNTRY = {
  name: 'Nigeria',
  dial_code: '+234',
  cca2: 'NG',
}

export const COUNTRIES = [
  { name: 'Afghanistan', dial_code: '+93', cca2: 'AF' },
  { name: 'Albania', dial_code: '+355', cca2: 'AL' },
  { name: 'Algeria', dial_code: '+213', cca2: 'DZ' },
  { name: 'Andorra', dial_code: '+376', cca2: 'AD' },
  { name: 'Angola', dial_code: '+244', cca2: 'AO' },
  { name: 'Antigua and Barbuda', dial_code: '+1268', cca2: 'AG' },
  { name: 'Argentina', dial_code: '+54', cca2: 'AR' },
  { name: 'Armenia', dial_code: '+374', cca2: 'AM' },
  { name: 'Australia', dial_code: '+61', cca2: 'AU' },
  { name: 'Austria', dial_code: '+43', cca2: 'AT' },
  { name: 'Azerbaijan', dial_code: '+994', cca2: 'AZ' },
  { name: 'Bahamas', dial_code: '+1242', cca2: 'BS' },
  { name: 'Bahrain', dial_code: '+973', cca2: 'BH' },
  { name: 'Bangladesh', dial_code: '+880', cca2: 'BD' },
  { name: 'Barbados', dial_code: '+1246', cca2: 'BB' },
  { name: 'Belarus', dial_code: '+375', cca2: 'BY' },
  { name: 'Belgium', dial_code: '+32', cca2: 'BE' },
  { name: 'Belize', dial_code: '+501', cca2: 'BZ' },
  { name: 'Benin', dial_code: '+229', cca2: 'BJ' },
  { name: 'Bhutan', dial_code: '+975', cca2: 'BT' },
  { name: 'Bolivia', dial_code: '+591', cca2: 'BO' },
  { name: 'Bosnia and Herzegovina', dial_code: '+387', cca2: 'BA' },
  { name: 'Botswana', dial_code: '+267', cca2: 'BW' },
  { name: 'Brazil', dial_code: '+55', cca2: 'BR' },
  { name: 'Brunei', dial_code: '+673', cca2: 'BN' },
  { name: 'Bulgaria', dial_code: '+359', cca2: 'BG' },
  { name: 'Burkina Faso', dial_code: '+226', cca2: 'BF' },
  { name: 'Burundi', dial_code: '+257', cca2: 'BI' },
  { name: 'Cabo Verde', dial_code: '+238', cca2: 'CV' },
  { name: 'Cambodia', dial_code: '+855', cca2: 'KH' },
  { name: 'Cameroon', dial_code: '+237', cca2: 'CM' },
  { name: 'Canada', dial_code: '+1', cca2: 'CA' },
  { name: 'Central African Republic', dial_code: '+236', cca2: 'CF' },
  { name: 'Chad', dial_code: '+235', cca2: 'TD' },
  { name: 'Chile', dial_code: '+56', cca2: 'CL' },
  { name: 'China', dial_code: '+86', cca2: 'CN' },
  { name: 'Colombia', dial_code: '+57', cca2: 'CO' },
  { name: 'Comoros', dial_code: '+269', cca2: 'KM' },
  { name: 'Congo (DRC)', dial_code: '+243', cca2: 'CD' },
  { name: 'Congo (Republic)', dial_code: '+242', cca2: 'CG' },
  { name: 'Costa Rica', dial_code: '+506', cca2: 'CR' },
  { name: "Côte d'Ivoire", dial_code: '+225', cca2: 'CI' },
  { name: 'Croatia', dial_code: '+385', cca2: 'HR' },
  { name: 'Cuba', dial_code: '+53', cca2: 'CU' },
  { name: 'Cyprus', dial_code: '+357', cca2: 'CY' },
  { name: 'Czechia', dial_code: '+420', cca2: 'CZ' },
  { name: 'Denmark', dial_code: '+45', cca2: 'DK' },
  { name: 'Djibouti', dial_code: '+253', cca2: 'DJ' },
  { name: 'Dominica', dial_code: '+1767', cca2: 'DM' },
  { name: 'Dominican Republic', dial_code: '+1809', cca2: 'DO' },
  { name: 'Ecuador', dial_code: '+593', cca2: 'EC' },
  { name: 'Egypt', dial_code: '+20', cca2: 'EG' },
  { name: 'El Salvador', dial_code: '+503', cca2: 'SV' },
  { name: 'Equatorial Guinea', dial_code: '+240', cca2: 'GQ' },
  { name: 'Eritrea', dial_code: '+291', cca2: 'ER' },
  { name: 'Estonia', dial_code: '+372', cca2: 'EE' },
  { name: 'Eswatini', dial_code: '+268', cca2: 'SZ' },
  { name: 'Ethiopia', dial_code: '+251', cca2: 'ET' },
  { name: 'Fiji', dial_code: '+679', cca2: 'FJ' },
  { name: 'Finland', dial_code: '+358', cca2: 'FI' },
  { name: 'France', dial_code: '+33', cca2: 'FR' },
  { name: 'Gabon', dial_code: '+241', cca2: 'GA' },
  { name: 'Gambia', dial_code: '+220', cca2: 'GM' },
  { name: 'Georgia', dial_code: '+995', cca2: 'GE' },
  { name: 'Germany', dial_code: '+49', cca2: 'DE' },
  { name: 'Ghana', dial_code: '+233', cca2: 'GH' },
  { name: 'Greece', dial_code: '+30', cca2: 'GR' },
  { name: 'Grenada', dial_code: '+1473', cca2: 'GD' },
  { name: 'Guatemala', dial_code: '+502', cca2: 'GT' },
  { name: 'Guinea', dial_code: '+224', cca2: 'GN' },
  { name: 'Guinea-Bissau', dial_code: '+245', cca2: 'GW' },
  { name: 'Guyana', dial_code: '+592', cca2: 'GY' },
  { name: 'Haiti', dial_code: '+509', cca2: 'HT' },
  { name: 'Honduras', dial_code: '+504', cca2: 'HN' },
  { name: 'Hong Kong', dial_code: '+852', cca2: 'HK' },
  { name: 'Hungary', dial_code: '+36', cca2: 'HU' },
  { name: 'Iceland', dial_code: '+354', cca2: 'IS' },
  { name: 'India', dial_code: '+91', cca2: 'IN' },
  { name: 'Indonesia', dial_code: '+62', cca2: 'ID' },
  { name: 'Iran', dial_code: '+98', cca2: 'IR' },
  { name: 'Iraq', dial_code: '+964', cca2: 'IQ' },
  { name: 'Ireland', dial_code: '+353', cca2: 'IE' },
  { name: 'Israel', dial_code: '+972', cca2: 'IL' },
  { name: 'Italy', dial_code: '+39', cca2: 'IT' },
  { name: 'Jamaica', dial_code: '+1876', cca2: 'JM' },
  { name: 'Japan', dial_code: '+81', cca2: 'JP' },
  { name: 'Jordan', dial_code: '+962', cca2: 'JO' },
  { name: 'Kazakhstan', dial_code: '+7', cca2: 'KZ' },
  { name: 'Kenya', dial_code: '+254', cca2: 'KE' },
  { name: 'Kiribati', dial_code: '+686', cca2: 'KI' },
  { name: 'Kosovo', dial_code: '+383', cca2: 'XK' },
  { name: 'Kuwait', dial_code: '+965', cca2: 'KW' },
  { name: 'Kyrgyzstan', dial_code: '+996', cca2: 'KG' },
  { name: 'Laos', dial_code: '+856', cca2: 'LA' },
  { name: 'Latvia', dial_code: '+371', cca2: 'LV' },
  { name: 'Lebanon', dial_code: '+961', cca2: 'LB' },
  { name: 'Lesotho', dial_code: '+266', cca2: 'LS' },
  { name: 'Liberia', dial_code: '+231', cca2: 'LR' },
  { name: 'Libya', dial_code: '+218', cca2: 'LY' },
  { name: 'Liechtenstein', dial_code: '+423', cca2: 'LI' },
  { name: 'Lithuania', dial_code: '+370', cca2: 'LT' },
  { name: 'Luxembourg', dial_code: '+352', cca2: 'LU' },
  { name: 'Madagascar', dial_code: '+261', cca2: 'MG' },
  { name: 'Malawi', dial_code: '+265', cca2: 'MW' },
  { name: 'Malaysia', dial_code: '+60', cca2: 'MY' },
  { name: 'Maldives', dial_code: '+960', cca2: 'MV' },
  { name: 'Mali', dial_code: '+223', cca2: 'ML' },
  { name: 'Malta', dial_code: '+356', cca2: 'MT' },
  { name: 'Marshall Islands', dial_code: '+692', cca2: 'MH' },
  { name: 'Mauritania', dial_code: '+222', cca2: 'MR' },
  { name: 'Mauritius', dial_code: '+230', cca2: 'MU' },
  { name: 'Mexico', dial_code: '+52', cca2: 'MX' },
  { name: 'Micronesia', dial_code: '+691', cca2: 'FM' },
  { name: 'Moldova', dial_code: '+373', cca2: 'MD' },
  { name: 'Monaco', dial_code: '+377', cca2: 'MC' },
  { name: 'Mongolia', dial_code: '+976', cca2: 'MN' },
  { name: 'Montenegro', dial_code: '+382', cca2: 'ME' },
  { name: 'Morocco', dial_code: '+212', cca2: 'MA' },
  { name: 'Mozambique', dial_code: '+258', cca2: 'MZ' },
  { name: 'Myanmar', dial_code: '+95', cca2: 'MM' },
  { name: 'Namibia', dial_code: '+264', cca2: 'NA' },
  { name: 'Nauru', dial_code: '+674', cca2: 'NR' },
  { name: 'Nepal', dial_code: '+977', cca2: 'NP' },
  { name: 'Netherlands', dial_code: '+31', cca2: 'NL' },
  { name: 'New Zealand', dial_code: '+64', cca2: 'NZ' },
  { name: 'Nicaragua', dial_code: '+505', cca2: 'NI' },
  { name: 'Niger', dial_code: '+227', cca2: 'NE' },
  { name: 'Nigeria', dial_code: '+234', cca2: 'NG' },
  { name: 'North Korea', dial_code: '+850', cca2: 'KP' },
  { name: 'North Macedonia', dial_code: '+389', cca2: 'MK' },
  { name: 'Norway', dial_code: '+47', cca2: 'NO' },
  { name: 'Oman', dial_code: '+968', cca2: 'OM' },
  { name: 'Pakistan', dial_code: '+92', cca2: 'PK' },
  { name: 'Palau', dial_code: '+680', cca2: 'PW' },
  { name: 'Palestine', dial_code: '+970', cca2: 'PS' },
  { name: 'Panama', dial_code: '+507', cca2: 'PA' },
  { name: 'Papua New Guinea', dial_code: '+675', cca2: 'PG' },
  { name: 'Paraguay', dial_code: '+595', cca2: 'PY' },
  { name: 'Peru', dial_code: '+51', cca2: 'PE' },
  { name: 'Philippines', dial_code: '+63', cca2: 'PH' },
  { name: 'Poland', dial_code: '+48', cca2: 'PL' },
  { name: 'Portugal', dial_code: '+351', cca2: 'PT' },
  { name: 'Qatar', dial_code: '+974', cca2: 'QA' },
  { name: 'Romania', dial_code: '+40', cca2: 'RO' },
  { name: 'Russia', dial_code: '+7', cca2: 'RU' },
  { name: 'Rwanda', dial_code: '+250', cca2: 'RW' },
  { name: 'Saint Kitts and Nevis', dial_code: '+1869', cca2: 'KN' },
  { name: 'Saint Lucia', dial_code: '+1758', cca2: 'LC' },
  { name: 'Saint Vincent and the Grenadines', dial_code: '+1784', cca2: 'VC' },
  { name: 'Samoa', dial_code: '+685', cca2: 'WS' },
  { name: 'San Marino', dial_code: '+378', cca2: 'SM' },
  { name: 'Sao Tome and Principe', dial_code: '+239', cca2: 'ST' },
  { name: 'Saudi Arabia', dial_code: '+966', cca2: 'SA' },
  { name: 'Senegal', dial_code: '+221', cca2: 'SN' },
  { name: 'Serbia', dial_code: '+381', cca2: 'RS' },
  { name: 'Seychelles', dial_code: '+248', cca2: 'SC' },
  { name: 'Sierra Leone', dial_code: '+232', cca2: 'SL' },
  { name: 'Singapore', dial_code: '+65', cca2: 'SG' },
  { name: 'Slovakia', dial_code: '+421', cca2: 'SK' },
  { name: 'Slovenia', dial_code: '+386', cca2: 'SI' },
  { name: 'Solomon Islands', dial_code: '+677', cca2: 'SB' },
  { name: 'Somalia', dial_code: '+252', cca2: 'SO' },
  { name: 'South Africa', dial_code: '+27', cca2: 'ZA' },
  { name: 'South Korea', dial_code: '+82', cca2: 'KR' },
  { name: 'South Sudan', dial_code: '+211', cca2: 'SS' },
  { name: 'Spain', dial_code: '+34', cca2: 'ES' },
  { name: 'Sri Lanka', dial_code: '+94', cca2: 'LK' },
  { name: 'Sudan', dial_code: '+249', cca2: 'SD' },
  { name: 'Suriname', dial_code: '+597', cca2: 'SR' },
  { name: 'Sweden', dial_code: '+46', cca2: 'SE' },
  { name: 'Switzerland', dial_code: '+41', cca2: 'CH' },
  { name: 'Syria', dial_code: '+963', cca2: 'SY' },
  { name: 'Taiwan', dial_code: '+886', cca2: 'TW' },
  { name: 'Tajikistan', dial_code: '+992', cca2: 'TJ' },
  { name: 'Tanzania', dial_code: '+255', cca2: 'TZ' },
  { name: 'Thailand', dial_code: '+66', cca2: 'TH' },
  { name: 'Timor-Leste', dial_code: '+670', cca2: 'TL' },
  { name: 'Togo', dial_code: '+228', cca2: 'TG' },
  { name: 'Tonga', dial_code: '+676', cca2: 'TO' },
  { name: 'Trinidad and Tobago', dial_code: '+1868', cca2: 'TT' },
  { name: 'Tunisia', dial_code: '+216', cca2: 'TN' },
  { name: 'Turkey', dial_code: '+90', cca2: 'TR' },
  { name: 'Turkmenistan', dial_code: '+993', cca2: 'TM' },
  { name: 'Tuvalu', dial_code: '+688', cca2: 'TV' },
  { name: 'Uganda', dial_code: '+256', cca2: 'UG' },
  { name: 'Ukraine', dial_code: '+380', cca2: 'UA' },
  { name: 'United Arab Emirates', dial_code: '+971', cca2: 'AE' },
  { name: 'United Kingdom', dial_code: '+44', cca2: 'GB' },
  { name: 'United States', dial_code: '+1', cca2: 'US' },
  { name: 'Uruguay', dial_code: '+598', cca2: 'UY' },
  { name: 'Uzbekistan', dial_code: '+998', cca2: 'UZ' },
  { name: 'Vanuatu', dial_code: '+678', cca2: 'VU' },
  { name: 'Vatican City', dial_code: '+379', cca2: 'VA' },
  { name: 'Venezuela', dial_code: '+58', cca2: 'VE' },
  { name: 'Vietnam', dial_code: '+84', cca2: 'VN' },
  { name: 'Yemen', dial_code: '+967', cca2: 'YE' },
  { name: 'Zambia', dial_code: '+260', cca2: 'ZM' },
  { name: 'Zimbabwe', dial_code: '+263', cca2: 'ZW' },
]