export const TOURS = {
  onboarding: [
    {
      id: 'welcome',
      target: null,
      manual: true,
      ctaLabel: 'Get Started',
      title: 'Welcome to TailorPady 👋',
      message: "Let's get you set up. It only takes a minute.",
    },
    {
      id: 'enable-notifications',
      target: '[data-tour="enable-notifications-btn"]',
      title: 'Turn on notifications',
      message: 'Tap here so you never miss an order, invoice, or birthday reminder.',
    },
    {
      id: 'install-app',
      target: '[data-tour="install-app-btn"]',
      title: 'Install the app',
      message: 'Tap here to install TailorPady on your device so you can use it offline.',
    },
    {
      id: 'confirm-start-customer',
      type: 'confirm',
      target: null,
      title: 'Ready to add your first customer?',
      message: "We'll walk through adding a customer, their measurements, an order, invoice, payment, and receipt.",
      yesLabel: "Let's go",
      noLabel: 'Maybe later',
    },
    {
      id: 'goto-customers-nav',
      target: '[data-tour="nav-customers"]',
      title: 'Go to Customers',
      message: 'Tap Customers in the bottom navigation.',
      count: { current: 1, total: 13 },
    },
    {
      id: 'add-customer',
      target: '[data-tour="add-customer-fab"]',
      title: 'Add your first customer',
      message: 'Every order starts with a customer profile. Tap the + button to add one.',
      count: { current: 2, total: 13 },
    },
    {
      id: 'tap-new-customer',
      target: '[data-tour="new-customer-row"]',
      title: 'Open their profile',
      message: 'Tap the customer you just added to open their profile.',
      count: { current: 3, total: 13 },
    },
    {
      id: 'add-measurement',
      target: '[data-tour="detail-fab"]',
      title: 'Add body measurements',
      message: 'Tap + to record their measurements. This is what orders are built from.',
      count: { current: 4, total: 13 },
    },
    {
      id: 'goto-orders-tab',
      target: '[data-tour="tab-orders"]',
      title: 'Now place an order',
      message: 'Tap the Orders tab.',
      count: { current: 5, total: 13 },
    },
    {
      id: 'add-order',
      target: '[data-tour="detail-fab"]',
      title: 'Add an order',
      message: 'Tap + to create an order using those measurements.',
      count: { current: 6, total: 13 },
    },
    {
      id: 'goto-invoices-tab',
      target: '[data-tour="tab-invoices"]',
      title: 'Generate an invoice',
      message: 'Tap the Invoices tab.',
      count: { current: 7, total: 13 },
    },
    {
      id: 'add-invoice',
      target: '[data-tour="detail-fab"]',
      title: 'Create the invoice',
      message: 'Tap + and select the order to generate an invoice.',
      count: { current: 8, total: 13 },
    },
    {
      id: 'goto-payments-tab',
      target: '[data-tour="tab-payments"]',
      title: 'Record a payment',
      message: 'Tap the Payments tab.',
      count: { current: 9, total: 13 },
    },
    {
      id: 'add-payment',
      target: '[data-tour="detail-fab"]',
      title: 'Record a payment',
      message: 'Tap + to record a payment for this order.',
      count: { current: 10, total: 13 },
    },
    {
      id: 'goto-receipts-tab',
      target: '[data-tour="tab-receipts"]',
      title: 'Get the receipt',
      message: 'Tap the Receipts tab.',
      count: { current: 11, total: 13 },
    },
    {
      id: 'add-receipt',
      target: '[data-tour="detail-fab"]',
      title: 'Generate a receipt',
      message: 'Tap + to generate a receipt from that payment.',
      count: { current: 12, total: 13 },
    },
    {
      id: 'done',
      target: null,
      title: "You're all set!",
      message: 'You now know the full flow: Customer, Measurements, Order, Invoice, Payment, Receipt.',
      count: { current: 13, total: 13 },
    },
  ],
}
