export const TOURS = {
  onboarding: [
    {
      id: 'welcome',
      target: null,
      manual: true,
      ctaLabel: 'Get Started',
      title: 'Welcome to TailorPady 👋',
      message: "Let's get you set up. It only takes a minute.",
      pages: ['/dashboard'],
    },
    {
      id: 'enable-notifications',
      target: '[data-tour="enable-notifications-btn"]',
      title: 'Turn on notifications',
      message: 'Tap here so you never miss an order, invoice, or birthday reminder.',
    },
    {
      id: 'install-app',
      target: '[data-tour="install-app-btn"]',
      title: 'Install the app',
      message: 'Tap here to install TailorPady on your device so you can use it even without internet.',
    },
    {
      id: 'fork-onboarding-path',
      type: 'branch',
      target: null,
      title: 'What would you like to do first?',
      message: "You can start by adding your first customer, or by setting up your business profile. Choose whichever one you'd like to do first.",
      continueLabel: 'Add customer',
      nextTarget: 'goto-customers-nav',
      viewLabel: 'Set up profile',
      viewTarget: 'highlight-profile-card',
      pages: ['/dashboard'],
    },
    {
      id: 'highlight-profile-card',
      target: '[data-tour="profile-setup-card"]',
      title: 'Complete your profile',
      message: 'Tap here to add your business name, logo, and other brand details.',
    },
    {
      id: 'highlight-edit-brand',
      target: '[data-tour="edit-brand-row"]',
      title: 'Set up your brand',
      message: 'Tap here to add your business name, logo, and brand colours.',
    },
    {
      id: 'highlight-edit-business-info',
      target: '[data-tour="edit-business-info-row"]',
      title: 'Add your business info',
      message: 'Tap here to add your phone number, email, address, and payment details.',
    },
    {
      id: 'confirm-add-customer-after-profile',
      type: 'confirm',
      target: null,
      title: 'Profile all set 🎉',
      message: 'Your business profile is ready. Would you like to add your first customer now?',
      yesLabel: "Let's go",
      noLabel: 'Not now',
      yesTarget: 'goto-customers-nav',
      noTarget: 'done',
      pages: ['/account'],
    },
    {
      id: 'goto-customers-nav',
      target: '[data-tour="nav-customers"]',
      desktopTarget: '[data-tour="sidebar-customers-nav"]',
      title: 'Go to Customers',
      message: 'Tap Customers in the bottom navigation.',
      desktopMessage: 'Tap Customers in the sidebar.',
      phase: 'Add Customer',
      count: { current: 1, total: 2 },
    },
    {
      id: 'add-customer',
      target: '[data-tour="add-customer-fab"]',
      title: 'Add your first customer',
      message: 'Tap the + button, fill in their details, and save.',
      phase: 'Add Customer',
      count: { current: 2, total: 2 },
    },
    {
      id: 'confirm-add-measurements',
      type: 'confirm',
      target: null,
      title: 'Customer added 🎉',
      message: 'Would you like to add their body measurements now? You will need these later when you create an order for them.',
      yesLabel: 'Add measurements',
      noLabel: 'Not now',
      noTarget: 'done',
      pages: ['/customers'],
    },
    {
      id: 'tap-new-customer',
      target: '[data-tour="new-customer-row"]',
      title: 'Open their profile',
      message: 'Tap the customer you just added to open their profile.',
      phase: 'Add Measurement',
      count: { current: 1, total: 2 },
    },
    {
      id: 'add-measurement',
      target: '[data-tour="detail-fab"]',
      title: 'Add body measurements',
      message: 'Tap + to record their measurements.',
      phase: 'Add Measurement',
      count: { current: 2, total: 2 },
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'branch-after-measurement',
      type: 'branch',
      target: null,
      title: 'Measurement saved 🎉',
      message: 'Would you like to see the details of the measurement you just saved, or go straight ahead and place an order for this customer?',
      viewLabel: 'View details',
      continueLabel: 'Create an order',
      viewTarget: 'view-new-measurement',
      nextTarget: 'goto-orders-tab',
      pages: ['/customers/'],
    },
    {
      id: 'view-new-measurement',
      target: '[data-tour="new-measurement-row"]',
      title: 'Tap to view details',
      message: 'Tap this card to see the measurement you just added.',
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'goto-orders-tab',
      target: '[data-tour="tab-orders"]',
      title: 'Now place an order',
      message: 'Tap the Orders tab.',
      phase: 'Add Order',
      count: { current: 1, total: 2 },
      padX: 2,
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'add-order',
      target: '[data-tour="detail-fab"]',
      title: 'Add an order',
      message: 'Tap + to create an order using those measurements.',
      phase: 'Add Order',
      count: { current: 2, total: 2 },
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'branch-after-order',
      type: 'branch',
      target: null,
      title: 'Order created 🎉',
      message: 'Would you like to see the details of the order you just created, or go ahead and create an invoice for it now?',
      viewLabel: 'View details',
      continueLabel: 'Create an invoice',
      viewTarget: 'view-new-order',
      nextTarget: 'goto-invoices-tab',
      pages: ['/customers/'],
    },
    {
      id: 'view-new-order',
      target: '[data-tour="new-order-row"]',
      title: 'Tap to view details',
      message: 'Tap this card to see the order you just created.',
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'goto-invoices-tab',
      target: '[data-tour="tab-invoices"]',
      title: 'Generate an invoice',
      message: 'Tap the Invoices tab.',
      phase: 'Generate Invoice',
      count: { current: 1, total: 2 },
      padX: 2,
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'add-invoice',
      target: '[data-tour="detail-fab"]',
      title: 'Create the invoice',
      message: 'Tap + and select the order you want to create an invoice for.',
      phase: 'Generate Invoice',
      count: { current: 2, total: 2 },
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'confirm-add-payment',
      type: 'confirm',
      target: null,
      title: 'Invoice created 🎉',
      message: 'Your invoice has been created. Would you like to record a payment for it now?',
      yesLabel: 'Record payment',
      noLabel: 'Not now',
      noTarget: 'done',
      pages: ['/customers/'],
    },
    {
      id: 'goto-payments-tab',
      target: '[data-tour="tab-payments"]',
      title: 'Record a payment',
      message: 'Tap the Payments tab.',
      phase: 'Record Payment',
      count: { current: 1, total: 2 },
      padX: 2,
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'add-payment',
      target: '[data-tour="detail-fab"]',
      title: 'Record a payment',
      message: 'Tap + to record a payment for this order.',
      phase: 'Record Payment',
      count: { current: 2, total: 2 },
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'branch-after-payment',
      type: 'branch',
      target: null,
      title: 'Payment recorded 🎉',
      message: 'Would you like to see the details of the payment you just recorded, or go ahead and generate a receipt for it now?',
      viewLabel: 'View details',
      continueLabel: 'Generate receipt',
      viewTarget: 'view-new-payment',
      nextTarget: 'goto-receipts-tab',
      pages: ['/customers/'],
    },
    {
      id: 'view-new-payment',
      target: '[data-tour="new-payment-row"]',
      title: 'Tap to view details',
      message: 'Tap this card to see the payment you just recorded.',
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'goto-receipts-tab',
      target: '[data-tour="tab-receipts"]',
      title: 'Generate a receipt',
      message: 'Tap the Receipts tab.',
      phase: 'Generate Receipt',
      count: { current: 1, total: 2 },
      padX: 2,
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'add-receipt',
      target: '[data-tour="detail-fab"]',
      title: 'Generate a receipt',
      message: 'Tap + to generate a receipt from that payment.',
      phase: 'Generate Receipt',
      count: { current: 2, total: 2 },
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'confirm-setup-profile-after-tour',
      type: 'confirm',
      target: null,
      title: 'One more thing 🎉',
      message: 'Would you like to set up your business profile now? This adds your business name, logo, and contact details to your invoices and receipts so they look more professional.',
      yesLabel: 'Set it up',
      noLabel: 'Maybe later',
      yesTarget: 'highlight-back-button',
      noTarget: 'done',
      pages: ['/customers/'],
    },
    {
      id: 'highlight-back-button',
      target: '[data-tour="tour-back-btn"]',
      title: 'Go back to Customers',
      message: 'Tap the back arrow to return to your customer list.',
      keepVisible: '[data-tour="customer-profile-block"]',
    },
    {
      id: 'highlight-hamburger',
      target: '[data-tour="tour-hamburger-btn"]',
      title: 'Open the menu',
      message: 'Tap the menu icon to open the side menu.',
    },
    {
      id: 'highlight-sidebar-account',
      target: '[data-tour="sidebar-account-nav"]',
      title: 'Go to Account',
      message: 'Tap Account to set up your profile.',
    },
    {
      id: 'done',
      target: null,
      title: "You're all set!",
      message: "You're ready to go. Everything you've learned works together to help you manage your tailoring business from start to finish. Explore the app and work the way that suits you best.",
    },
  ],

  'portfolio-setup': [
    {
      id: 'portfolio-welcome',
      target: null,
      manual: true,
      ctaLabel: 'Get Started',
      title: 'Set up your portfolio 🎨',
      message: 'Turn your best work into a public showcase clients can browse and share.',
      pages: ['/portfolio'],
    },
    {
      id: 'portfolio-choose-template',
      target: '[data-tour="portfolio-template-picker"]',
      title: 'Choose a template',
      message: 'Pick the layout that best fits your brand. You can switch templates any time.',
    },
    {
      id: 'portfolio-edit-hero',
      target: '[data-tour="portfolio-hero-edit"]',
      title: 'Set your hero section',
      message: 'Add a headline and cover photo that introduces your brand.',
      phase: 'Hero',
      count: { current: 1, total: 1 },
    },
    {
      id: 'portfolio-edit-about',
      target: '[data-tour="portfolio-about-edit"]',
      title: 'Tell your story',
      message: 'Add an about section so clients know who they are working with.',
      phase: 'About',
      count: { current: 1, total: 1 },
    },
    {
      id: 'portfolio-add-collection',
      target: '[data-tour="portfolio-add-collection-btn"]',
      title: 'Add a collection',
      message: 'Upload photos of your work and group them into a collection.',
      phase: 'Collection',
      count: { current: 1, total: 2 },
    },
    {
      id: 'portfolio-order-collection-items',
      target: '[data-tour="portfolio-collection-list"]',
      title: 'Arrange your work',
      message: 'Drag to reorder items so your strongest pieces show first.',
      phase: 'Collection',
      count: { current: 2, total: 2 },
    },
    {
      id: 'portfolio-edit-contact',
      target: '[data-tour="portfolio-contact-edit"]',
      title: 'Add your contact details',
      message: 'Add a phone number, email, or WhatsApp link so clients can reach you directly.',
    },
    {
      id: 'confirm-portfolio-publish',
      type: 'confirm',
      target: null,
      title: 'Looking good 🎉',
      message: 'Your portfolio is ready. Would you like to publish it now?',
      yesLabel: 'Publish',
      noLabel: 'Not yet',
      yesTarget: 'portfolio-publish-btn',
      noTarget: 'portfolio-done',
      pages: ['/portfolio'],
    },
    {
      id: 'portfolio-publish-btn',
      target: '[data-tour="portfolio-publish-btn"]',
      title: 'Publish your portfolio',
      message: 'Tap here to make your portfolio live and get your shareable link.',
    },
    {
      id: 'portfolio-done',
      target: null,
      title: "You're all set!",
      message: 'Your portfolio is ready to share with clients. You can keep editing it any time from this page.',
    },
  ],

  'ai-assistant': [
    {
      id: 'ai-welcome',
      target: null,
      manual: true,
      ctaLabel: 'Get Started',
      title: 'Meet your AI assistant 🤖',
      message: 'Your assistant can answer questions about your business and help you get things done faster.',
      pages: ['/assistant'],
    },
    {
      id: 'ai-open-chat',
      target: '[data-tour="ai-assistant-fab"]',
      title: 'Open the assistant',
      message: 'Tap here any time to start a conversation with your assistant.',
    },
    {
      id: 'ai-ask-question',
      target: '[data-tour="ai-chat-input"]',
      title: 'Ask it anything',
      message: 'Try asking something like "Which customers have unpaid invoices this week?"',
      phase: 'Ask',
      count: { current: 1, total: 1 },
    },
    {
      id: 'ai-suggested-prompts',
      target: '[data-tour="ai-suggested-prompts"]',
      title: 'Not sure what to ask?',
      message: 'Tap a suggested prompt to see what your assistant can help with.',
    },
    {
      id: 'ai-quick-actions',
      target: '[data-tour="ai-quick-actions"]',
      title: 'Take action from chat',
      message: 'Your assistant can create tasks, draft messages, and pull up records without leaving the chat.',
    },
    {
      id: 'ai-done',
      target: null,
      title: "You're ready to go!",
      message: 'Use your assistant whenever you need a quick answer or a hand with your daily tasks.',
    },
  ],
}
