import { USAGE_LIMITS } from '../datas/usageLimits'

export const FREE_FEATURES = [
  { icon: 'group', label: `Up to ${USAGE_LIMITS.customers} customers (lifetime limit)` },
  { icon: 'straighten', label: `${USAGE_LIMITS.measurementsPerMonth} measurements / month` },
  { icon: 'receipt_long', label: `${USAGE_LIMITS.ordersPerMonth} orders / month` },
  { icon: 'description', label: 'Access to all invoice & receipt templates' },
  { icon: 'print', label: `${USAGE_LIMITS.invoicesPerMonth} invoices / month` },
  { icon: 'receipt', label: `${USAGE_LIMITS.receiptsPerMonth} receipts / month` },
  { icon: 'palette', label: 'Basic brand customization (logo, colors, and business details)' },
  { icon: 'link', label: 'Fully branded public portfolio page with shareable link' },
  { icon: 'photo_library', label: `${USAGE_LIMITS.portfolioUploadsPerMonth} portfolio image uploads / month` },
  { icon: 'star_rate', label: `${USAGE_LIMITS.reviewLinksPerMonth} review links / month` },
  { icon: 'payments', label: `${USAGE_LIMITS.paymentRecordsPerMonth} payment records / month` },
  { icon: 'smart_toy', label: `${USAGE_LIMITS.aiActionsPerMonth} AI assistant actions / month` },
  { icon: 'cake', label: 'Customer birthday reminders' },
  { icon: 'inventory_2', label: 'Inventory tracking' },
  { icon: 'checklist', label: 'Task management' },
  { icon: 'event', label: 'Appointment scheduling' },
  { icon: 'bar_chart', label: 'Business reports (orders, customers, appointments, tasks, and revenue)' },
]

export const PRO_FEATURES = [
  { icon: 'group', label: 'Unlimited customers, no lifetime cap' },
  { icon: 'straighten', label: 'Unlimited measurements / month' },
  { icon: 'receipt_long', label: 'Unlimited orders / month' },
  { icon: 'description', label: 'Access to all invoice & receipt templates' },
  { icon: 'print', label: 'Unlimited invoices / month' },
  { icon: 'receipt', label: 'Unlimited receipts / month' },
  { icon: 'palette', label: 'Full brand customization: logo, colors, signature & business details' },
  { icon: 'account_balance', label: 'Bank details & terms and conditions on every document' },
  { icon: 'link', label: 'Fully branded public portfolio page with shareable link' },
  { icon: 'photo_library', label: 'Unlimited portfolio image uploads' },
  { icon: 'star_rate', label: 'Unlimited review links' },
  { icon: 'payments', label: 'Unlimited payment records with advanced tracking' },
  { icon: 'smart_toy', label: 'Unlimited AI assistant actions' },
  { icon: 'cake', label: 'Customer birthday reminders' },
  { icon: 'inventory_2', label: 'Inventory tracking' },
  { icon: 'checklist', label: 'Task management' },
  { icon: 'event', label: 'Appointment scheduling' },
  { icon: 'bar_chart', label: 'Advanced business reports (orders, customers, appointments, tasks, and revenue)' },
  { icon: 'edit_note', label: 'Smart invoice auto-drafts' },
  { icon: 'campaign', label: 'Customer re-engagement reminders' },
  { icon: 'cloud', label: 'Expanded cloud storage' },
]
